# Generated by Django 6.0.3 on 2026-03-21 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidders', '0001_initial'),
        ('documents', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCheckSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('homepage_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'external_checks_source',
            },
        ),
        migrations.CreateModel(
            name='BidderMemberExternalCheck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_type', models.CharField(max_length=50)),
                ('query_value', models.CharField(max_length=255)),
                ('result_status', models.CharField(choices=[('not_run', 'No ejecutada'), ('no_match', 'Sin coincidencia'), ('match', 'Con coincidencia'), ('inconclusive', 'No concluyente'), ('error', 'Error')], default='not_run', max_length=20)),
                ('raw_result_payload', models.JSONField(blank=True, default=dict)),
                ('consulted_at', models.DateTimeField(blank=True, null=True)),
                ('requires_human_review', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_checks', to='bidders.bidder')),
                ('bidder_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_checks', to='bidders.biddermember')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('evidence_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_checks', to='documents.documentversion')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_checks', to='procurement.contractprocess')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='external_checks.biddermemberexternalcheck')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checks', to='external_checks.externalchecksource')),
            ],
            options={
                'db_table': 'external_checks_bidder_member_check',
                'indexes': [models.Index(fields=['process', 'bidder', 'result_status'], name='external_ch_process_7402ed_idx'), models.Index(fields=['bidder_member', 'source'], name='external_ch_bidder__b927cf_idx')],
            },
        ),
    ]
