# Generated by Django 6.0.3 on 2026-03-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_checks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biddermemberexternalcheck',
            options={'verbose_name': 'Consulta externa de integrante', 'verbose_name_plural': 'Consultas externas de integrantes'},
        ),
        migrations.AlterModelOptions(
            name='externalchecksource',
            options={'verbose_name': 'Fuente de consulta externa', 'verbose_name_plural': 'Fuentes de consultas externas'},
        ),
    ]
