# Generated by Django 6.0.3 on 2026-03-21 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidders', '0001_initial'),
        ('documents', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RUPFieldSchema',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=30)),
                ('is_required', models.BooleanField(default=False)),
                ('validation_hint', models.CharField(blank=True, max_length=255)),
                ('applies_to_process_type', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rup_rup_field_schema',
            },
        ),
        migrations.CreateModel(
            name='RUPRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('validity_note', models.TextField(blank=True)),
                ('raw_extracted_payload', models.JSONField(default=dict)),
                ('review_status', models.CharField(choices=[('not_evaluated', 'No evaluado'), ('preliminar', 'Preliminar'), ('needs_human_review', 'Requiere revision humana'), ('confirmed', 'Confirmado'), ('adjusted_by_human', 'Ajustado por humano'), ('rejected', 'Rechazado'), ('obsolete', 'Obsoleto'), ('voided', 'Anulado')], default='not_evaluated', max_length=32)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rup_records', to='bidders.bidder')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rup_records', to='procurement.contractprocess')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rup_records', to='documents.documentversion')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='rup.ruprecord')),
            ],
            options={
                'db_table': 'rup_rup_record',
            },
        ),
        migrations.CreateModel(
            name='RUPFieldValue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('value_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document_page_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rup_field_values', to='documents.documentpageref')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='rup.rupfieldschema')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='rup.rupfieldvalue')),
                ('rup_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='rup.ruprecord')),
            ],
            options={
                'db_table': 'rup_rup_field_value',
            },
        ),
        migrations.CreateModel(
            name='RUPCodeEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_type', models.CharField(max_length=50)),
                ('code_value', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document_page_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rup_codes', to='documents.documentpageref')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='rup.rupcodeentry')),
                ('rup_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='rup.ruprecord')),
            ],
            options={
                'db_table': 'rup_rup_code_entry',
            },
        ),
        migrations.CreateModel(
            name='RUPSegmentEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('segment_code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document_page_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rup_segments', to='documents.documentpageref')),
                ('rup_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='rup.ruprecord')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='rup.rupsegmententry')),
            ],
            options={
                'db_table': 'rup_rup_segment_entry',
            },
        ),
        migrations.AddIndex(
            model_name='rupfieldschema',
            index=models.Index(fields=['is_active', 'sort_order'], name='rup_rup_fie_is_acti_dda77c_idx'),
        ),
        migrations.AddIndex(
            model_name='ruprecord',
            index=models.Index(fields=['process', 'bidder'], name='rup_rup_rec_process_e4f0ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='ruprecord',
            constraint=models.UniqueConstraint(fields=('bidder', 'version_no'), name='uq_rup_record_bidder_version'),
        ),
        migrations.AddIndex(
            model_name='rupfieldvalue',
            index=models.Index(fields=['rup_record', 'schema'], name='rup_rup_fie_rup_rec_fe47f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='rupfieldvalue',
            constraint=models.UniqueConstraint(fields=('rup_record', 'schema', 'version_no'), name='uq_rup_field_value_version'),
        ),
        migrations.AddIndex(
            model_name='rupcodeentry',
            index=models.Index(fields=['rup_record', 'code_type', 'code_value'], name='rup_rup_cod_rup_rec_ce1b15_idx'),
        ),
        migrations.AddIndex(
            model_name='rupsegmententry',
            index=models.Index(fields=['rup_record', 'segment_code'], name='rup_rup_seg_rup_rec_a02603_idx'),
        ),
    ]
