# Generated by Django 6.0.3 on 2026-03-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rupcodeentry',
            options={'verbose_name': 'Entrada de codigo RUP', 'verbose_name_plural': 'Entradas de codigos RUP'},
        ),
        migrations.AlterModelOptions(
            name='rupfieldschema',
            options={'verbose_name': 'Esquema de campo RUP', 'verbose_name_plural': 'Esquemas de campos RUP'},
        ),
        migrations.AlterModelOptions(
            name='rupfieldvalue',
            options={'verbose_name': 'Valor de campo RUP', 'verbose_name_plural': 'Valores de campos RUP'},
        ),
        migrations.AlterModelOptions(
            name='ruprecord',
            options={'verbose_name': 'Registro RUP', 'verbose_name_plural': 'Registros RUP'},
        ),
        migrations.AlterModelOptions(
            name='rupsegmententry',
            options={'verbose_name': 'Entrada de segmento RUP', 'verbose_name_plural': 'Entradas de segmentos RUP'},
        ),
    ]
