# Generated by Django 6.0.3 on 2026-03-21 22:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('identification_type', models.CharField(max_length=30)),
                ('identification_number', models.CharField(max_length=50)),
                ('bidder_type', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('registered', 'Registrado'), ('documents_pending', 'Documentos pendientes'), ('under_validation', 'En validacion'), ('with_alerts', 'Con alertas'), ('with_suggested_rejection', 'Con causal sugerida'), ('eligible_for_review', 'Listo para revision'), ('finalized', 'Finalizado'), ('closed_snapshot', 'Congelado al cierre')], default='registered', max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidders', to='procurement.contractprocess')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bidders_bidder',
            },
        ),
        migrations.CreateModel(
            name='BidderMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('identification_type', models.CharField(max_length=30)),
                ('identification_number', models.CharField(max_length=50)),
                ('member_role', models.CharField(blank=True, max_length=50)),
                ('participation_percentage', models.DecimalField(decimal_places=4, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_lead', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='bidders.bidder')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bidders_bidder_member',
            },
        ),
        migrations.AddIndex(
            model_name='bidder',
            index=models.Index(fields=['process', 'state'], name='bidders_bid_process_66c6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='bidder',
            index=models.Index(fields=['identification_number'], name='bidders_bid_identif_603e26_idx'),
        ),
        migrations.AddConstraint(
            model_name='bidder',
            constraint=models.UniqueConstraint(fields=('process', 'identification_type', 'identification_number'), name='uq_bidder_process_identification'),
        ),
        migrations.AddIndex(
            model_name='biddermember',
            index=models.Index(fields=['bidder', 'is_lead'], name='bidders_bid_bidder__380c10_idx'),
        ),
        migrations.AddConstraint(
            model_name='biddermember',
            constraint=models.UniqueConstraint(fields=('bidder', 'identification_type', 'identification_number'), name='uq_bidder_member_identification'),
        ),
    ]
