# Generated by Django 6.0.3 on 2026-03-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidder',
            options={'verbose_name': 'Proponente', 'verbose_name_plural': 'Proponentes'},
        ),
        migrations.AlterModelOptions(
            name='biddermember',
            options={'verbose_name': 'Integrante del proponente', 'verbose_name_plural': 'Integrantes del proponente'},
        ),
    ]
