# Generated by Django 6.0.3 on 2026-03-21 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTypeFamily',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('modality', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'normative_document_type_family',
            },
        ),
        migrations.CreateModel(
            name='DocumentTypeVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_label', models.CharField(max_length=100)),
                ('resolution_reference', models.CharField(blank=True, max_length=255)),
                ('official_url', models.URLField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='normative.documenttypefamily')),
            ],
            options={
                'db_table': 'normative_document_type_version',
            },
        ),
        migrations.CreateModel(
            name='DocumentTypeArtifact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('artifact_type', models.CharField(max_length=50)),
                ('official_url', models.URLField(blank=True)),
                ('file_hash', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='normative.documenttypeversion')),
            ],
            options={
                'db_table': 'normative_document_type_artifact',
            },
        ),
        migrations.CreateModel(
            name='NormativeSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_label', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('checksum', models.CharField(max_length=128)),
                ('is_current', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document_type_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='normative.documenttypeversion')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normative_snapshots', to='procurement.contractprocess')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='normative.normativesnapshot')),
            ],
            options={
                'db_table': 'normative_snapshot',
            },
        ),
        migrations.CreateModel(
            name='NormativeSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('homepage_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'normative_source',
            },
        ),
        migrations.AddField(
            model_name='documenttypefamily',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='families', to='normative.normativesource'),
        ),
        migrations.CreateModel(
            name='ProcessNormativeBinding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('current_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_bindings', to='normative.normativesnapshot')),
                ('document_type_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_bindings', to='normative.documenttypeversion')),
                ('process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normative_binding', to='procurement.contractprocess')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_process_normative_binding',
            },
        ),
        migrations.AddIndex(
            model_name='documenttypeversion',
            index=models.Index(fields=['family', 'is_active'], name='normative_d_family__4449cf_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttypeversion',
            index=models.Index(fields=['valid_from', 'valid_to'], name='normative_d_valid_f_622014_idx'),
        ),
        migrations.AddConstraint(
            model_name='documenttypeversion',
            constraint=models.UniqueConstraint(fields=('family', 'version_label'), name='uq_document_type_version_label'),
        ),
        migrations.AddIndex(
            model_name='documenttypeartifact',
            index=models.Index(fields=['version', 'artifact_type'], name='normative_d_version_0d9719_idx'),
        ),
        migrations.AddIndex(
            model_name='normativesnapshot',
            index=models.Index(fields=['process', 'is_current'], name='normative_s_process_d513e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='normativesnapshot',
            constraint=models.UniqueConstraint(fields=('process', 'version_no'), name='uq_normative_snapshot_process_version'),
        ),
        migrations.AddConstraint(
            model_name='normativesnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('process',), name='uq_current_normative_snapshot_per_process'),
        ),
        migrations.AddIndex(
            model_name='documenttypefamily',
            index=models.Index(fields=['sector', 'modality'], name='normative_d_sector_7b5ea9_idx'),
        ),
    ]
