# Generated by Django 6.0.3 on 2026-03-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normative', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttypeartifact',
            options={'verbose_name': 'Artefacto normativo', 'verbose_name_plural': 'Artefactos normativos'},
        ),
        migrations.AlterModelOptions(
            name='documenttypefamily',
            options={'verbose_name': 'Familia de documento tipo', 'verbose_name_plural': 'Familias de documentos tipo'},
        ),
        migrations.AlterModelOptions(
            name='documenttypeversion',
            options={'verbose_name': 'Version de documento tipo', 'verbose_name_plural': 'Versiones de documentos tipo'},
        ),
        migrations.AlterModelOptions(
            name='normativesnapshot',
            options={'verbose_name': 'Snapshot normativo', 'verbose_name_plural': 'Snapshots normativos'},
        ),
        migrations.AlterModelOptions(
            name='normativesource',
            options={'verbose_name': 'Fuente normativa', 'verbose_name_plural': 'Fuentes normativas'},
        ),
        migrations.AlterModelOptions(
            name='processnormativebinding',
            options={'verbose_name': 'Vinculo normativo del proceso', 'verbose_name_plural': 'Vinculos normativos del proceso'},
        ),
    ]
