# Generated by Django 6.0.3 on 2026-03-21 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidders', '0001_initial'),
        ('documents', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialInputVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_label', models.CharField(max_length=255)),
                ('source_date', models.DateField()),
                ('assets_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('liabilities_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('operating_income_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('financial_observation', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Radicado'), ('superseded', 'Reemplazado')], default='draft', max_length=16)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_inputs', to='bidders.bidder')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_inputs', to='procurement.contractprocess')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_inputs', to='documents.documentversion')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='finance.financialinputversion')),
            ],
            options={
                'db_table': 'finance_financial_input_version',
            },
        ),
        migrations.CreateModel(
            name='FinancialAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_code', models.CharField(choices=[('meets', 'Cumple'), ('not_meets', 'No cumple'), ('conditional', 'Condicionado'), ('pending', 'Pendiente')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('preliminar', 'Preliminar'), ('confirmed', 'Confirmado'), ('obsolete', 'Obsoleto'), ('voided', 'Anulado')], default='preliminar', max_length=16)),
                ('assessment_note', models.TextField(blank=True)),
                ('human_required', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('used_in_consolidation', models.BooleanField(default=False)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_assessments', to='bidders.bidder')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_assessments', to='procurement.contractprocess')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_assessments_reviewed', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='finance.financialassessment')),
                ('financial_input_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='finance.financialinputversion')),
            ],
            options={
                'db_table': 'finance_financial_assessment',
            },
        ),
        migrations.AddIndex(
            model_name='financialinputversion',
            index=models.Index(fields=['process', 'bidder', 'status'], name='finance_fin_process_e1bbd9_idx'),
        ),
        migrations.AddIndex(
            model_name='financialinputversion',
            index=models.Index(fields=['source_date'], name='finance_fin_source__b3c089_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialinputversion',
            constraint=models.UniqueConstraint(fields=('bidder', 'version_no'), name='uq_financial_input_bidder_version'),
        ),
        migrations.AddConstraint(
            model_name='financialinputversion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('bidder',), name='uq_single_financial_input_draft_per_bidder'),
        ),
        migrations.AddIndex(
            model_name='financialassessment',
            index=models.Index(fields=['process', 'bidder', 'status'], name='finance_fin_process_8b8936_idx'),
        ),
        migrations.AddIndex(
            model_name='financialassessment',
            index=models.Index(fields=['used_in_consolidation'], name='finance_fin_used_in_199891_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialassessment',
            constraint=models.UniqueConstraint(fields=('bidder', 'version_no'), name='uq_financial_assessment_bidder_version'),
        ),
        migrations.AddConstraint(
            model_name='financialassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('used_in_consolidation', True)), fields=('bidder',), name='uq_single_financial_assessment_in_consolidation_per_bidder'),
        ),
    ]
