# Generated by Django 6.0.3 on 2026-03-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialassessment',
            options={'verbose_name': 'Evaluacion financiera', 'verbose_name_plural': 'Evaluaciones financieras'},
        ),
        migrations.AlterModelOptions(
            name='financialinputversion',
            options={'verbose_name': 'Version de insumo financiero', 'verbose_name_plural': 'Versiones de insumos financieros'},
        ),
    ]
