# Generated by Django 6.0.3 on 2026-03-21 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidders', '0001_initial'),
        ('normative', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidatedMatrixSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot_label', models.CharField(max_length=100)),
                ('data_fingerprint', models.CharField(max_length=128)),
                ('serialized_matrix_payload', models.JSONField(default=dict)),
                ('is_current', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrix_snapshots_generated', to=settings.AUTH_USER_MODEL)),
                ('normative_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrix_snapshots', to='normative.normativesnapshot')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrix_snapshots', to='procurement.contractprocess')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='consolidation.consolidatedmatrixsnapshot')),
            ],
            options={
                'db_table': 'consolidation_matrix_snapshot',
            },
        ),
        migrations.CreateModel(
            name='BidderConsolidatedResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('technical_result', models.CharField(choices=[('meets', 'Cumple'), ('not_meets', 'No cumple'), ('conditional', 'Condicionado'), ('pending', 'Pendiente')], default='pending', max_length=20)),
                ('rup_result', models.CharField(choices=[('meets', 'Cumple'), ('not_meets', 'No cumple'), ('conditional', 'Condicionado'), ('pending', 'Pendiente')], default='pending', max_length=20)),
                ('experience_general_result', models.CharField(choices=[('meets', 'Cumple'), ('not_meets', 'No cumple'), ('conditional', 'Condicionado'), ('pending', 'Pendiente')], default='pending', max_length=20)),
                ('experience_specific_result', models.CharField(choices=[('meets', 'Cumple'), ('not_meets', 'No cumple'), ('conditional', 'Condicionado'), ('pending', 'Pendiente')], default='pending', max_length=20)),
                ('financial_result', models.CharField(choices=[('meets', 'Cumple'), ('not_meets', 'No cumple'), ('conditional', 'Condicionado'), ('pending', 'Pendiente')], default='pending', max_length=20)),
                ('rejection_result', models.CharField(choices=[('meets', 'Cumple'), ('not_meets', 'No cumple'), ('conditional', 'Condicionado'), ('pending', 'Pendiente')], default='pending', max_length=20)),
                ('final_result', models.CharField(choices=[('meets', 'Cumple'), ('not_meets', 'No cumple'), ('conditional', 'Condicionado'), ('pending', 'Pendiente')], default='pending', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('trace_payload', models.JSONField(default=dict)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consolidated_results', to='bidders.bidder')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bidder_consolidated_results', to='procurement.contractprocess')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='consolidation.bidderconsolidatedresult')),
                ('matrix_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bidder_results', to='consolidation.consolidatedmatrixsnapshot')),
            ],
            options={
                'db_table': 'consolidation_bidder_consolidated_result',
            },
        ),
        migrations.CreateModel(
            name='FinalReportVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/')),
                ('file_hash', models.CharField(blank=True, max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('matrix_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_report_versions', to='consolidation.consolidatedmatrixsnapshot')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_report_versions', to='procurement.contractprocess')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='consolidation.finalreportversion')),
            ],
            options={
                'db_table': 'reports_final_report_version',
            },
        ),
        migrations.AddIndex(
            model_name='consolidatedmatrixsnapshot',
            index=models.Index(fields=['process', 'is_current'], name='consolidati_process_ccb7d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='consolidatedmatrixsnapshot',
            constraint=models.UniqueConstraint(fields=('process', 'version_no'), name='uq_matrix_snapshot_process_version'),
        ),
        migrations.AddConstraint(
            model_name='consolidatedmatrixsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('process',), name='uq_current_matrix_snapshot_per_process'),
        ),
        migrations.AddIndex(
            model_name='bidderconsolidatedresult',
            index=models.Index(fields=['process', 'bidder'], name='consolidati_process_981848_idx'),
        ),
        migrations.AddIndex(
            model_name='bidderconsolidatedresult',
            index=models.Index(fields=['final_result'], name='consolidati_final_r_a9e28a_idx'),
        ),
        migrations.AddIndex(
            model_name='finalreportversion',
            index=models.Index(fields=['process', 'version_no'], name='reports_fin_process_d90c91_idx'),
        ),
    ]
