# Generated by Django 6.0.3 on 2026-03-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consolidation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidderconsolidatedresult',
            options={'verbose_name': 'Resultado consolidado por proponente', 'verbose_name_plural': 'Resultados consolidados por proponente'},
        ),
        migrations.AlterModelOptions(
            name='consolidatedmatrixsnapshot',
            options={'verbose_name': 'Snapshot de matriz consolidada', 'verbose_name_plural': 'Snapshots de matrices consolidadas'},
        ),
        migrations.AlterModelOptions(
            name='finalreportversion',
            options={'verbose_name': 'Version de informe final', 'verbose_name_plural': 'Versiones de informes finales'},
        ),
    ]
