# Generated by Django 6.0.3 on 2026-03-21 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidders', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=50)),
                ('classification', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('replaced', 'Reemplazado'), ('voided', 'Anulado')], default='active', max_length=16)),
                ('is_required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bidders.bidder')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='procurement.contractprocess')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_document',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_hash', models.CharField(max_length=128)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('replaced', 'Reemplazado'), ('voided', 'Anulado')], default='active', max_length=16)),
                ('is_current', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='documents.documentversion')),
            ],
            options={
                'db_table': 'documents_document_version',
            },
        ),
        migrations.CreateModel(
            name='DocumentPageRef',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('extracted_text', models.TextField(blank=True)),
                ('extraction_confidence', models.CharField(choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja'), ('not_applicable', 'No aplica')], default='not_applicable', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_refs', to='documents.documentversion')),
            ],
            options={
                'db_table': 'documents_document_page_ref',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['process', 'document_type'], name='documents_d_process_20fbe0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['bidder', 'classification'], name='documents_d_bidder__708929_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'is_current'], name='documents_d_documen_4d5ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['file_hash'], name='documents_d_file_ha_ce00a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_no'), name='uq_document_version_number'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('document',), name='uq_current_document_version_per_document'),
        ),
        migrations.AddIndex(
            model_name='documentpageref',
            index=models.Index(fields=['document_version', 'page_number'], name='documents_d_documen_a2f85d_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentpageref',
            constraint=models.UniqueConstraint(fields=('document_version', 'page_number'), name='uq_document_page_ref'),
        ),
    ]
