# Generated by Django 6.0.3 on 2026-03-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
        migrations.AlterModelOptions(
            name='documentpageref',
            options={'verbose_name': 'Referencia de pagina de documento', 'verbose_name_plural': 'Referencias de pagina de documento'},
        ),
        migrations.AlterModelOptions(
            name='documentversion',
            options={'verbose_name': 'Version de documento', 'verbose_name_plural': 'Versiones de documentos'},
        ),
    ]
