# Generated by Django 6.0.3 on 2026-03-21 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidders', '0001_initial'),
        ('evaluation', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionCauseDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_subsanable', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], default='high', max_length=16)),
                ('human_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_cause_definitions', to='procurement.contractprocess')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'causals_rejection_cause_definition',
            },
        ),
        migrations.CreateModel(
            name='RejectionCauseAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_triggered', 'No activada'), ('alert_detected', 'Alerta detectada'), ('suggested', 'Sugerida'), ('under_review', 'En revision'), ('confirmed', 'Confirmada'), ('dismissed', 'Descartada'), ('obsolete', 'Obsoleta')], default='not_triggered', max_length=20)),
                ('origin_type', models.CharField(default='mixed', max_length=20)),
                ('is_subsanable', models.BooleanField(default=False)),
                ('evidence_summary', models.TextField(blank=True)),
                ('human_review_required', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('impact_on_closure', models.BooleanField(default=False)),
                ('impact_on_final_status', models.CharField(blank=True, max_length=20)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rejection_cause_assessments', to='bidders.bidder')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rejection_cause_assessments', to='procurement.contractprocess')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejection_cause_assessments_reviewed', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='causals.rejectioncauseassessment')),
                ('triggering_decision_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triggered_rejection_causes', to='evaluation.validationdecisionrecord')),
                ('cause_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='causals.rejectioncausedefinition')),
            ],
            options={
                'db_table': 'causals_rejection_cause_assessment',
            },
        ),
        migrations.AddIndex(
            model_name='rejectioncausedefinition',
            index=models.Index(fields=['process', 'is_active'], name='causals_rej_process_50952d_idx'),
        ),
        migrations.AddConstraint(
            model_name='rejectioncausedefinition',
            constraint=models.UniqueConstraint(fields=('process', 'code'), name='uq_rejection_cause_definition_process_code'),
        ),
        migrations.AddIndex(
            model_name='rejectioncauseassessment',
            index=models.Index(fields=['process', 'bidder', 'status'], name='causals_rej_process_e691af_idx'),
        ),
        migrations.AddIndex(
            model_name='rejectioncauseassessment',
            index=models.Index(fields=['impact_on_closure'], name='causals_rej_impact__053c4a_idx'),
        ),
    ]
