# Generated by Django 6.0.3 on 2026-03-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rejectioncauseassessment',
            options={'verbose_name': 'Evaluacion de causal de rechazo', 'verbose_name_plural': 'Evaluaciones de causales de rechazo'},
        ),
        migrations.AlterModelOptions(
            name='rejectioncausedefinition',
            options={'verbose_name': 'Definicion de causal de rechazo', 'verbose_name_plural': 'Definiciones de causales de rechazo'},
        ),
    ]
