# Generated by Django 6.0.3 on 2026-03-21 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidders', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=50)),
                ('object_type', models.CharField(max_length=100)),
                ('object_uuid', models.UUIDField()),
                ('action', models.CharField(max_length=100)),
                ('before_payload', models.JSONField(blank=True, default=dict)),
                ('after_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('bidder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='bidders.bidder')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='procurement.contractprocess')),
            ],
            options={
                'db_table': 'audit_audit_event',
                'indexes': [models.Index(fields=['process', 'created_at'], name='audit_audit_process_284437_idx'), models.Index(fields=['object_type', 'object_uuid'], name='audit_audit_object__2c8f8c_idx'), models.Index(fields=['module', 'event_type'], name='audit_audit_module_9169d9_idx')],
            },
        ),
    ]
