# Generated by Django 6.0.3 on 2026-03-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'verbose_name': 'Evento de auditoria', 'verbose_name_plural': 'Eventos de auditoria'},
        ),
    ]
