# Generated by Django 6.0.3 on 2026-03-21 22:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidders', '0001_initial'),
        ('documents', '0001_initial'),
        ('procurement', '0001_initial'),
        ('rules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_identifier', models.CharField(max_length=100)),
                ('contract_type', models.CharField(max_length=100)),
                ('contract_object', models.TextField()),
                ('contractor_role', models.CharField(blank=True, max_length=50)),
                ('contract_value_nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('contract_currency', models.CharField(default='COP', max_length=10)),
                ('contract_year', models.PositiveIntegerField(blank=True, null=True)),
                ('execution_start_date', models.DateField(blank=True, null=True)),
                ('execution_end_date', models.DateField(blank=True, null=True)),
                ('execution_length_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('execution_length_unit', models.CharField(blank=True, max_length=30)),
                ('participation_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_general_experience_candidate', models.BooleanField(default=True)),
                ('is_specific_experience_candidate', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('not_evaluated', 'No evaluado'), ('preliminar', 'Preliminar'), ('needs_human_review', 'Requiere revision humana'), ('confirmed', 'Confirmado'), ('adjusted_by_human', 'Ajustado por humano'), ('rejected', 'Rechazado'), ('obsolete', 'Obsoleto'), ('voided', 'Anulado')], default='not_evaluated', max_length=32)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_records', to='bidders.bidder')),
                ('bidder_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experience_records', to='bidders.biddermember')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_records', to='procurement.contractprocess')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experience_records', to='documents.documentversion')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='experience.experiencerecord')),
            ],
            options={
                'db_table': 'experience_experience_record',
            },
        ),
        migrations.CreateModel(
            name='ExperienceMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_code', models.CharField(max_length=100)),
                ('metric_value_number', models.DecimalField(decimal_places=4, max_digits=20)),
                ('metric_unit', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=30)),
                ('calculation_trace', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('document_page_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='experience_metrics', to='documents.documentpageref')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='experience.experiencemetric')),
                ('experience_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='experience.experiencerecord')),
            ],
            options={
                'db_table': 'experience_experience_metric',
            },
        ),
        migrations.CreateModel(
            name='ExperienceAssessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('general', 'General'), ('specific', 'Especifica')], max_length=16)),
                ('is_valid', models.BooleanField(default=False)),
                ('rejection_reason_code', models.CharField(blank=True, max_length=100)),
                ('accepted_contribution_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('accepted_contribution_unit', models.CharField(blank=True, max_length=30)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_assessments', to='bidders.bidder')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_assessments', to='procurement.contractprocess')),
                ('rule_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_assessments', to='rules.ruledefinition')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_assessments', to='rules.ruleversion')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='experience.experienceassessment')),
                ('experience_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='experience.experiencerecord')),
            ],
            options={
                'db_table': 'experience_experience_assessment',
            },
        ),
        migrations.CreateModel(
            name='MinimumWageYear',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'experience_minimum_wage_year',
            },
        ),
        migrations.CreateModel(
            name='SMMLVConversionRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('resulting_smmlv', models.DecimalField(decimal_places=4, max_digits=20)),
                ('calculation_trace', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('experience_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smmlv_conversions', to='experience.experiencerecord')),
                ('minimum_wage_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversions', to='experience.minimumwageyear')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='experience.smmlvconversionrecord')),
            ],
            options={
                'db_table': 'experience_smmlv_conversion_record',
            },
        ),
        migrations.CreateModel(
            name='ExperienceConsolidation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('general', 'General'), ('specific', 'Especifica')], max_length=16)),
                ('total_valid_contracts', models.PositiveIntegerField(default=0)),
                ('total_accepted_value', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('total_accepted_smmlv', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('meets_requirement', models.BooleanField(default=False)),
                ('consolidation_trace', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('not_evaluated', 'No evaluado'), ('preliminar', 'Preliminar'), ('needs_human_review', 'Requiere revision humana'), ('confirmed', 'Confirmado'), ('adjusted_by_human', 'Ajustado por humano'), ('rejected', 'Rechazado'), ('obsolete', 'Obsoleto'), ('voided', 'Anulado')], default='preliminar', max_length=32)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_consolidations', to='bidders.bidder')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experience_consolidations', to='procurement.contractprocess')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='experience.experienceconsolidation')),
            ],
            options={
                'db_table': 'experience_experience_consolidation',
                'indexes': [models.Index(fields=['process', 'bidder', 'scope'], name='experience__process_80615c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='experiencerecord',
            index=models.Index(fields=['bidder', 'contract_identifier'], name='experience__bidder__5af8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencerecord',
            index=models.Index(fields=['process', 'bidder_member'], name='experience__process_65c531_idx'),
        ),
        migrations.AddIndex(
            model_name='experiencemetric',
            index=models.Index(fields=['experience_record', 'metric_code'], name='experience__experie_d584fc_idx'),
        ),
        migrations.AddIndex(
            model_name='experienceassessment',
            index=models.Index(fields=['bidder', 'scope', 'is_valid'], name='experience__bidder__d67b17_idx'),
        ),
        migrations.AddIndex(
            model_name='experienceassessment',
            index=models.Index(fields=['experience_record', 'scope'], name='experience__experie_b17d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='smmlvconversionrecord',
            index=models.Index(fields=['experience_record', 'minimum_wage_year'], name='experience__experie_de96d6_idx'),
        ),
    ]
