# Generated by Django 6.0.3 on 2026-03-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experienceassessment',
            options={'verbose_name': 'Evaluacion de experiencia', 'verbose_name_plural': 'Evaluaciones de experiencia'},
        ),
        migrations.AlterModelOptions(
            name='experienceconsolidation',
            options={'verbose_name': 'Consolidacion de experiencia', 'verbose_name_plural': 'Consolidaciones de experiencia'},
        ),
        migrations.AlterModelOptions(
            name='experiencemetric',
            options={'verbose_name': 'Metrica de experiencia', 'verbose_name_plural': 'Metricas de experiencia'},
        ),
        migrations.AlterModelOptions(
            name='experiencerecord',
            options={'verbose_name': 'Contrato de experiencia', 'verbose_name_plural': 'Contratos de experiencia'},
        ),
        migrations.AlterModelOptions(
            name='minimumwageyear',
            options={'verbose_name': 'SMMLV por ano', 'verbose_name_plural': 'SMMLV por ano'},
        ),
        migrations.AlterModelOptions(
            name='smmlvconversionrecord',
            options={'verbose_name': 'Conversion a SMMLV', 'verbose_name_plural': 'Conversiones a SMMLV'},
        ),
    ]
