# Generated by Django 6.0.3 on 2026-03-21 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('normative', '0001_initial'),
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=50)),
                ('rule_type', models.CharField(choices=[('boolean', 'Booleana'), ('threshold', 'Umbral'), ('code_list', 'Lista de codigos'), ('aggregation', 'Agregacion'), ('percentage', 'Porcentaje'), ('document_presence', 'Presencia documental'), ('composite', 'Compuesta')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_human_required', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rules_rule_definition',
            },
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_label', models.CharField(max_length=50)),
                ('parameters', models.JSONField(default=dict)),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Critica')], default='medium', max_length=16)),
                ('is_subsanable', models.BooleanField(default=False)),
                ('human_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('checksum', models.CharField(max_length=128)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('normative_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rule_versions', to='normative.normativesnapshot')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rule_versions', to='procurement.contractprocess')),
                ('rule_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='rules.ruledefinition')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_set', to='rules.ruleversion')),
            ],
            options={
                'db_table': 'rules_rule_version',
            },
        ),
        migrations.CreateModel(
            name='ProcessRuleActivation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('activation_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_activations', to='procurement.contractprocess')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('rule_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_activations', to='rules.ruledefinition')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activations', to='rules.ruleversion')),
            ],
            options={
                'db_table': 'rules_process_rule_activation',
            },
        ),
        migrations.AddIndex(
            model_name='ruledefinition',
            index=models.Index(fields=['module', 'rule_type'], name='rules_rule__module_d6df30_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleversion',
            index=models.Index(fields=['process', 'is_active'], name='rules_rule__process_3233b2_idx'),
        ),
        migrations.AddIndex(
            model_name='ruleversion',
            index=models.Index(fields=['rule_definition', 'is_active'], name='rules_rule__rule_de_22dc32_idx'),
        ),
        migrations.AddConstraint(
            model_name='ruleversion',
            constraint=models.UniqueConstraint(fields=('rule_definition', 'version_no', 'process'), name='uq_rule_version_process_number'),
        ),
        migrations.AddIndex(
            model_name='processruleactivation',
            index=models.Index(fields=['process', 'is_active'], name='rules_proce_process_baa2eb_idx'),
        ),
        migrations.AddConstraint(
            model_name='processruleactivation',
            constraint=models.UniqueConstraint(fields=('process', 'rule_version'), name='uq_process_rule_activation'),
        ),
        migrations.AddConstraint(
            model_name='processruleactivation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('process', 'rule_definition'), name='uq_active_rule_definition_per_process'),
        ),
    ]
