# Generated by Django 6.0.3 on 2026-03-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processruleactivation',
            options={'verbose_name': 'Activacion de regla del proceso', 'verbose_name_plural': 'Activaciones de reglas del proceso'},
        ),
        migrations.AlterModelOptions(
            name='ruledefinition',
            options={'verbose_name': 'Definicion de regla', 'verbose_name_plural': 'Definiciones de reglas'},
        ),
        migrations.AlterModelOptions(
            name='ruleversion',
            options={'verbose_name': 'Version de regla', 'verbose_name_plural': 'Versiones de reglas'},
        ),
    ]
