# Generated by Django 6.0.3 on 2026-03-21 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractProcess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.PositiveIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('entity_name', models.CharField(max_length=255)),
                ('process_type', models.CharField(max_length=100)),
                ('modality', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('draft', 'Borrador'), ('normative_bound', 'Base normativa vinculada'), ('configured', 'Configurado'), ('in_evaluation', 'En evaluacion'), ('under_review', 'En revision'), ('ready_for_closure', 'Listo para cierre'), ('closed', 'Cerrado'), ('archived', 'Archivado')], default='draft', max_length=32)),
                ('current_rule_bundle_version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_contract_process',
            },
        ),
        migrations.CreateModel(
            name='ProcessTeamMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='procurement.contractprocess')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'procurement_process_team_member',
            },
        ),
        migrations.AddIndex(
            model_name='contractprocess',
            index=models.Index(fields=['state', 'modality'], name='procurement_state_3a41ca_idx'),
        ),
        migrations.AddIndex(
            model_name='contractprocess',
            index=models.Index(fields=['opening_date', 'closing_date'], name='procurement_opening_943510_idx'),
        ),
        migrations.AddConstraint(
            model_name='processteammember',
            constraint=models.UniqueConstraint(fields=('process', 'user', 'role_code'), name='uq_process_team_member_role'),
        ),
    ]
