# Generated by Django 6.0.3 on 2026-03-22 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractprocess',
            options={'verbose_name': 'Proceso de contratacion', 'verbose_name_plural': 'Procesos de contratacion'},
        ),
        migrations.AlterModelOptions(
            name='processteammember',
            options={'verbose_name': 'Integrante del equipo del proceso', 'verbose_name_plural': 'Integrantes del equipo del proceso'},
        ),
    ]
